@startuml
left to right direction
skinparam actorstyle awesome
actor Utente as u
rectangle Calcolatrice{
    usecase "Effettua un operazione" as UC1
    usecase "Inserisci un numero nello Stack" as UC2
    (Input non valido) .> (UC2) : <<extends>>
    (Input non valido) .> (UC1) : <<extends>>
    (UC1) --.> (Operazioni matematiche su un operando) : <<include>>
    (UC1) --.> (Operazioni matematiche su due operandi) : <<include>>
    (UC1) --.> (Operazioni di manipolazione dello stack) : <<include>>
    (UC1) --.> (Operazioni che riguardano le variabili supportate dalla calcolatrice) : <<include>>
    (Operazioni matematiche su due operandi) <.- (Stack vuoto o con un solo elemento) : <<extends>>
    (Operazioni matematiche su un operando) <.- (Stack vuoto) : <<extends>>
    (Operazioni di manipolazione dello stack) <.- (Stack vuoto o non sufficiaentemente popolato \n per le operazioni di "dup", "swap", "over") : <<extends>>
    (Operazioni che riguardano le variabili supportate dalla calcolatrice) <.- (Stack vuoto o variabile scelta \n non inizializzata) : <<extends>>
}
u -- UC1
u -- UC2
@enduml